### ISSUE TITLE
Admin samples give 404 (OSOE-791)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Data-Tables#157]
These two go to 404:

![301333510-d97e7e9a-2aaa-4a52-aa43-f580dcd19ec1](https://github.com/Lombiq/Orchard-Data-Tables/assets/1976647/87a48f12-39db-449f-8b1c-60b895220852)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-791)

**Comment by sarahelsaig** [comment]
Turns out it was a bug with `TypedRoute` link generation, not specific to Data Tables. ~Though when you visit any of the DT pages it only shows an empty table with no data. So there is still some problem.~ nvm I forgor the sample recipe
